
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Runtime.Hotfix
{
public sealed partial class monster : Luban.BeanBase
{
    public monster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ResKey = _buf.ReadString();
        Hp = _buf.ReadInt();
        Atk = _buf.ReadInt();
        Speed = _buf.ReadFloat();
    }

    public static monster Deserializemonster(ByteBuf _buf)
    {
        return new monster(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 资源地址
    /// </summary>
    public readonly string ResKey;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Atk;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
   
    public const int __ID__ = 1236617178;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "resKey:" + ResKey + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "speed:" + Speed + ","
        + "}";
    }
}
}

