
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Runtime.Hotfix
{
public partial class Tables
{
    public Tbhero Tbhero {get; }
    public Tbmonster Tbmonster {get; }

	public System.Collections.Generic.Dictionary<string, ICfgAble> AllData {get;private set;} = new System.Collections.Generic.Dictionary<string, ICfgAble>();
    
	public Tables(System.Func<string, ByteBuf> loader)
    {
        Tbhero = new Tbhero(loader("tbhero"));
        AllData.Add(Tbhero.CfgName,Tbhero);
        Tbmonster = new Tbmonster(loader("tbmonster"));
        AllData.Add(Tbmonster.CfgName,Tbmonster);
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbhero.ResolveRef(this);
        Tbmonster.ResolveRef(this);
    }
}

}
