
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Runtime.Hotfix
{
public partial class Tbhero : ICfgAble
{
    private readonly System.Collections.Generic.Dictionary<int, hero> _dataMap;
    private readonly System.Collections.Generic.List<hero> _dataList;
    
	public static string CfgName = "Tbhero";
	public static Tbhero Data{ get { return Global.gApp.gCfgMgr.GetData<Tbhero>(CfgName); } }
    
	public Tbhero(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, hero>(n);
        _dataList = new System.Collections.Generic.List<hero>(n);
        for(int i = n ; i > 0 ; --i)
        {
            hero _v;
            _v = global::Game.Runtime.Hotfix.hero.Deserializehero(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, hero> DataMap => _dataMap;
    public System.Collections.Generic.List<hero> DataList => _dataList;

    public hero GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public hero Get(int key) => _dataMap[key];
    public hero this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

