
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Runtime.Hotfix
{
public partial class Tbmonster : ICfgAble
{
    private readonly System.Collections.Generic.Dictionary<int, monster> _dataMap;
    private readonly System.Collections.Generic.List<monster> _dataList;
    
	public static string CfgName = "Tbmonster";
	public static Tbmonster Data{ get { return Global.gApp.gCfgMgr.GetData<Tbmonster>(CfgName); } }
    
	public Tbmonster(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, monster>(n);
        _dataList = new System.Collections.Generic.List<monster>(n);
        for(int i = n ; i > 0 ; --i)
        {
            monster _v;
            _v = global::Game.Runtime.Hotfix.monster.Deserializemonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, monster> DataMap => _dataMap;
    public System.Collections.Generic.List<monster> DataList => _dataList;

    public monster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public monster Get(int key) => _dataMap[key];
    public monster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

