
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Runtime.Hotfix
{
public partial class Tables
{
    public Tbitem Tbitem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Tbitem = new Tbitem(loader("tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
    }
}

}
