
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Runtime.Hotfix
{
public partial class Tbitem
{
    private readonly System.Collections.Generic.Dictionary<int, item> _dataMap;
    private readonly System.Collections.Generic.List<item> _dataList;
    
    public Tbitem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, item>(n);
        _dataList = new System.Collections.Generic.List<item>(n);
        for(int i = n ; i > 0 ; --i)
        {
            item _v;
            _v = global::Game.Runtime.Hotfix.item.Deserializeitem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item> DataMap => _dataMap;
    public System.Collections.Generic.List<item> DataList => _dataList;

    public item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public item Get(int key) => _dataMap[key];
    public item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

